### ISSUE TITLE
work on entity alignment

### ISSUE THREAD

**Issue by john012343210** [ThiviyanThanapalasingam/relational-GraphConvolutionNetwork#9]
does r-gcn works on entity alignment (existing R-GCN seems only focus on classification and link prediction)?

If yes, May I know do you have any working code on this?

or does this link prediction model works directly on that? Since “Links between two nodes exist” is very similar to “two nodes referring to same real-world object”

**Comment by thiviyanT** [comment]
Hi! 

Thank you for your interest in the code.

The main focus of [our work](https://arxiv.org/abs/2107.10015) was to reproduce the experiments (node classification and link prediction) from the original paper and provide an intuitive explanation on how RGCNs work. Therefore, we do not have an implementation of an RGCN-based entity alignment model.

I think this would require some significant changes to the model. A naive approach would be to embed the KGs and then compare the distances between all nodes in the vector space. Nodes that refer to the same entity should be closer to each other in the vector space. However, doing this in a computationally efficient manner would be quite challenging.

As you pointed out, you could also frame this problem as a link prediction task. However, this would involve changing the input data slightly. You would have to combine the two KGs into a single relational graph and then provide some examples of the "same as" links that connect entities from one graph to those in the second graph. 

You might also be interested in this paper which outlines an architecture for performing entity alignment with promising results: https://www.ijcai.org/proceedings/2019/0733.pdf. 

I hope you found this useful!
